### ISSUE TITLE
Visualisation: Show the total results returned with the search results

### ISSUE THREAD

**Issue by Samwalton9** [Samwalton9/WikiCiteVis#19]
Above or below the search results, the 'count' should be shown.

**Comment by davidcmoulton** [comment]
This is implemented in https://github.com/Samwalton9/WikiCiteVis/pull/37 in the following format
<img width="999" alt="screenshot 2018-07-20 13 33 22" src="https://user-images.githubusercontent.com/2893480/43002668-7dac3900-8c21-11e8-94e2-e400546c9840.png">
